### PR TITLE
Added Battery Notifier, Time Notifier and PC_Info Displayer. 

### PR DESCRIPTION
**Pull request by encrypted-jpg**

### CODE REVIEW

**Comment by encrypted-jpg** [comment]
I've Added the battery, Time Notifier and PC info file. Check it out and let me know your suggestions.

**Review by prashantsengar — CHANGES_REQUESTED** [review]
Please make the code modular. You can define a new module just for the notification function and call it whenever you need it

**Comment by prashantsengar** [comment]
You have done a great work @encrypted-jpg ! 

Please see my comment above. 

And I would like to know a few more things please
1. Why did you choose the subprocess module, and not the `psutil` module? Not saying that it is wrong but I want to know the reason :) Will it work on both Linux and Windows?
2. Why time notifier? What purpose does it serve for any person. Does it solve something for you? Just want to understand it from your point of view :)
3. Is it necessary to have both .pyw and .py files? Won't it be better to use only one extension and let the user change it accordingly. We can add the instructions in readme.

Apart from that, other few suggestions.
1. Please make different PRs for different additions. It makes it easier to review and test.
2. Can we give the user an option to choose what he wants to run at a single point?

You have done a wonderful job. Congratulations on this PR 🥳

**Comment by encrypted-jpg** [comment]
Thanks for your suggestions.. @prashantsengar 
1. Actually, I'm not familiar with `psutil` module, 
   and I've written many other programs with `subprocess` module.
   I've used the Battery_Notifier Commands and PC_Info Commands that are applicable for windows.
2. Time Notifier Program notifies the user every half-an-hour to take breaks and also time and how many hours.
    This helps to know the time spent.
3. Yeah! It's better to keep only file with one extension. I'll change the readme for this one.
4. OK. I'll make separate PR's for separate files.
5. We can give the user an option to choose, but we need to code it a single file or make classes for every program. I think if we use different files 
   it would be easier for the user to schedule it at startup as they are notifiers.
6. About the code modular, I think the `win10toast` module itself only does one function i.e., notifying, So, I didn't
   understand why we need to code another class/module to do the same work.

**Comment by prashantsengar** [comment]
@encrypted-jpg 
1. I think using `psutil` will be a better option because it abstracts functions for each platform and the code looks cleaner.
2. Can we change this to notify the user to something like **breathe** or **blink**? Feels good that my PC reminds me to breathe to be mindful. I already have such a script running for me.
6. It's not about `win10toast`, it's about being platform independent. You can define a new file called `notify.py` and implement a function called `notify` there with the required params. Check what the current OS is, if windows, call win10toast. If Linux, I think there is a command which can be called using either `os.system` or `subprocess` module

**Comment by encrypted-jpg** [comment]
1. I've Changed the Battery Notifier program such that it notifies when battery is less than 30  and greater than 80. 
2. It also save the usage stats during discharging and charging to refer in future for any purpose. It can also used to check the charge per minute (charging rate) or minutes per 1 percent charge (discharging rate) using minutes and charge columns in the csv file. 
3. Here I've used the `py-notifier` module which is a cross-platform module (working with win10 and linux) and `psutil` module is used for getting battery info.

**Comment by prashantsengar** [comment]
You did a great job, Aditya!
I was actually wondering if I should include all of these files here or should directly move to https://github.com/SweetPC
What do you suggest?

**Comment by encrypted-jpg** [comment]
@prashantsengar 
Thanks for that...
As the Name suggests cleanpy is about cleaning and filtering files, So adding it to sweetpc is better in my view.
Also Include only the Battery_Notifier file, Now I'm working on Time_Notifier and Large_files_info issues.
Finally my intention of saving data in battery_notifier.py file is that I want to use that data to make a Machine Learning model by Regression Algorithm to predict how much time do the battery last with the help of usage stats, when the data I have is sufficient enough.

**Comment by prashantsengar** [comment]
Cool, can you also tell me the difference between `win10toast` and `win10toast_persist` that you have used?

**Comment by encrypted-jpg** [comment]
With `win10toast` module you can only display the notifications with a fixed duration, but with `win10toast_persist` those notifications will persist for specified time duration. I didn't use those modules in battery_notifier.py and i'll change those modules to `pynotifier` in other files as it is cross-platform compatible.

**Comment by prashantsengar** [comment]
Sure, I will start the porting work to SweetPC

**Comment by encrypted-jpg** [comment]
I've Added GUI for Time Notifier file.
Functionality:
1. Notifies you for every 20min with a gui window which has "always on top" functionality i.e., even you open another app it will be on top of that app.
2. It displays 2 buttons snooze and go for next. Snooze - It notifies you again after 5 min. Go for Next - It skips this breaks and notify you after 20 min.
3. For every hour you will get a Notification (not in the form of gui). 
4. It also displays a quote at the below of the window.

**Pull request closed without merging**
